### ISSUE TITLE
Kali support

### ISSUE THREAD

**Issue by KBeDeveloper** [gyazo/Gyazo-for-Linux#123]
Please add **apt-get** support to Kali Linux. 
packagescloud.io OS verification fails.

**Comment by Shellbme21** [comment]
Shelly A. Robertson

On Dec 8, 2018 9:00 AM, "Benjamin Calisto" <notifications@github.com> wrote:

Please add *apt-get* support to Kali Linux.
packagescloud.io OS verification fails.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gyazo/Gyazo-for-Linux/issues/123>, or mute the thread

**Comment by pastak** [comment]
@KBeDeveloper I think  Kali Linux is based on Debian. So please you would try to https://github.com/gyazo/Gyazo-for-Linux/issues/35

**Comment by KBeDeveloper** [comment]
> @KBeDeveloper I think Kali Linux is based on Debian. So please you would try to #35

Yes, <a href="https://github.com/gyazo/Gyazo-for-Linux/issues/35#issuecomment-386000518" target="_blank">this</a> worked for me. Thank you for the answer.

**Comment by pastak** [comment]
good luck!
