### ISSUE TITLE
Unable to dowload repo config

### ISSUE THREAD

**Issue by nexik** [gyazo/Gyazo-for-Linux#35]
After running 

curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash

curl: (22) The requested URL returned error: 404 Not Found
Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=LinuxMint&dist=rafaela&name=nexik-Lenovo&source=script

**Comment by pastak** [comment]
@nexik thank you for your report. We support only Debian / Ubuntu or RedHat / CentOS. 

I remember Linux Mint rafaela is based on Ubuntu 14.04. ( is it correct? )

I have wrote shell script https://gist.github.com/pastak/2b2ecfa3edf369f3f3bd . In this script, I set target os is ubuntu 14.04.

Please try to exec it and we'll be happy for your success to install :smile: 

`% curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash`

**Comment by nexik** [comment]
yep it solve the problem

**Comment by pepperonas** [comment]
Nice, worked like a charm. Thanks!

**Comment by theoldfellow** [comment]
Brilliant, thank you.

**Comment by Desmaster** [comment]
Solved the problem! Thanks!

**Comment by BookCase** [comment]
![gyazo_fail](https://cloud.githubusercontent.com/assets/6614806/10900918/fe6e8604-81b3-11e5-99ea-0b7cf312e92c.png)

I had the same issue installing on Ubuntu 15.10 (32-Bit). This action has also solved the issue for me.

**Comment by pastak** [comment]
We have forgot to release for Ubuntu 15.10. I'll make it issue :-P

**Comment by pastak** [comment]
We handled to install for Linux Mint, Fedora and some distributions supported by packagecloud.

Please have fun with Gyazo!!!

**Comment by BookCase** [comment]
Good deal! :+1:

**Comment by fercreek** [comment]
@pastak like a boss!! :+1:

**Comment by adriancs35** [comment]
@pastak No package found for LinuxMint Serena.

**Comment by pastak** [comment]
@adriancs35 Thanks for your report. I published package for linuxmint/serena

**Comment by jingle0927** [comment]
jingle@jingle:~$ curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as Deepin/unstable.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...curl: (22) The requested URL returned error: 404 Not Found


Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=Deepin&dist=unstable&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.

**Comment by pastak** [comment]
@jingle0927 We don't know about Deepin well. Please try to do as help message you paste. Deepin maybe distribution based on Debian. So you should try to `os=debian dist=jessie curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash`

**Comment by ProfessorStupid** [comment]
The OS override hasn't seemed to have worked for me.  Here is the output of the script:

`
os=ubuntu dist=xenial curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as elementary/loki.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...curl: (22) The requested URL returned error: 404 Not Found


Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=elementary&dist=loki&source=script

This usually happens if your operating system is not supported by 
packagecloud.io, or this script's OS detection failed.

You can override the OS detection by setting os= and dist= prior to running this script.
You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version

For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh

If you are running a supported OS, please email support@packagecloud.io and report this.
`

As Elementary OS is based on Ubuntu 16.04, that is the version I selected for the script to grab.

**Comment by pastak** [comment]
@ProfessorStupid hmmm...  It seems correct to exec install script.

Please try to https://github.com/gyazo/Gyazo-for-Linux/issues/35#issuecomment-138102251 🙏

**Comment by ProfessorStupid** [comment]
@pastak that has sorted it, thank you!

**Comment by CodeNoxy** [comment]
> Detected operating system as Kali/kali-rolling.
> Checking for curl...
> Detected curl...
> Checking for gpg...
> Detected gpg...
> Running apt-get update... done.
> Installing apt-transport-https... done.
> Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...curl: (22) The requested URL returned error: 404 Not Found
> 
> Unable to download repo config from: https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/config_file.list?os=Kali&dist=kali-rolling&source=script
> 
> This usually happens if your operating system is not supported by 
> packagecloud.io, or this script's OS detection failed.
> 
> You can override the OS detection by setting os= and dist= prior to running this script.
> You can find a list of supported OSes and distributions on our website: https://packagecloud.io/docs#os_distro_version
> 
> For example, to force Ubuntu Trusty: os=ubuntu dist=trusty ./script.sh
> 
> If you are running a supported OS, please email support@packagecloud.io and report this.

I'm running Kali (Debian). I tried the comment #35 but, still getting issues.

**Comment by pastak** [comment]
@CodeNoxy Please try `curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo os=debian dist=jessie bash`

**Comment by jtkinchen** [comment]
> @nexik thank you for your report. We support only Debian / Ubuntu or RedHat / CentOS.
> 
> I remember Linux Mint rafaela is based on Ubuntu 14.04. ( is it correct? )
> 
> I have wrote shell script https://gist.github.com/pastak/2b2ecfa3edf369f3f3bd . In this script, I set target os is ubuntu 14.04.
> 
> Please try to exec it and we'll be happy for your success to install smile
> 
> `% curl -s https://gist.githubusercontent.com/pastak/2b2ecfa3edf369f3f3bd/raw/1d1961c24f62cf11782fa9f2851e305922dc871e/gistfile.sh | sudo bash`

Still working on Mint 19.3 Tricia, just set the dist variable in the shell script to dist="bionic"

**Comment by prawn185** [comment]
Can we get support for PopOS please! - Based off of Ubuntu

**Comment by trushkina** [comment]
Hello! After running
xxx:~$ sudo curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as Ubuntu/lunar.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.6.0
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/gyazo_gyazo-for-linux-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
xxx:~$ sudo apt-get install gyazo
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
E: Невозможно найти пакет gyazo

Description:    Ubuntu 23.04 (64-bit)

**Comment by rvvslv** [comment]
Hi

Please release version for Ubuntu 23.04 Lunar

**Comment by kcwebby** [comment]
Mantic?

``` Err:11 https://packagecloud.io/gyazo/gyazo-for-linux/ubuntu mantic Release
  404  Not Found [IP: 54.176.122.186 443]
Reading package lists... Done ```

```curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
Detected operating system as Ubuntu/mantic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Detected apt version as 2.7.3
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/gyazo_gyazo-for-linux.list...done.
Importing packagecloud gpg key... Packagecloud gpg key imported to /etc/apt/keyrings/gyazo_gyazo-for-linux-archive-keyring.gpg
done.
Running apt-get update... done.

The repository is setup! You can now install packages.
brian@ls-ws-ubuntu2:~/Documents$ sudo apt install gyazo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package gyazo```

**Comment by jdreina7** [comment]
Same problem with `Kubuntu 23.04`

```shell
root@user-that-rocks:/# sudo apt-get install gyazo
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias... Hecho
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete gyazo
``` 
![image](https://github.com/gyazo/Gyazo-for-Linux/assets/28866324/b0cce23b-68c5-45c6-9b09-8dd64040e703)
