### ISSUE TITLE
Which GPL License?

### ISSUE THREAD

**Issue by bmintz** [gyazo/Gyazo-for-Linux#62]
Sorry "the GPL license" means _any_ version.

Please specify the GPL version you want.

Personally I recommend GPLv2, but that's just me. See [what Torvalds said about it for details](https://www.youtube.com/watch?v=PaKIZ7gJlRU). But that's just one side of the coin. There's other opinions too, and software license version numbers don't work like software version numbers.

**Comment by drobune** [comment]
Thank you for your report.
We have not yet indicate licence versions.

I think ”GPLv2 or any later version” is proper for Gyazo-for-Linux.
Because it is better that many people use Gyazo than patent protection.

I want to ask contributors @kambara @yaa @mattn @imkitchen @ujihisa @uiureo @pastak @nna774 @rakusai 
for the opinion.

**Comment by ujihisa** [comment]
Personally I prefer "GPLv3 or any later versions" instead of 2+, particularly for protecting users from patent, but yes I'm fine with your suggestion "GPLv2 or any later versions" as well.

:+1:
